# sources.yaml

# Міністерство у справах ветеранів України — категорія "Новини"
- name: "Мінветеранів — новини"
  list_urls:
    - "https://mva.gov.ua/category/86-novini"
  link_selector: "a[href*='/prescenter/category/']"
  max_per_source: 10
  detail:
    title_selectors: ["h1", ".page-title", ".node__title"]
    summary_selectors: ["article p", ".content p", ".node__content p"]
    date_selectors: ["time[datetime]", "meta[property='article:published_time']", ".field--name-created", ".date", ".published"]
    date_attr: "datetime"

# Урядовий портал — тег "ветерани"
- name: "КМУ — ветерани (тег)"
  list_urls:
    - "https://www.kmu.gov.ua/tags/veterany"
  link_selector: ".news-list a, article a, a[href*='/news/']"
  max_per_source: 8
  detail:
    title_selectors: ["h1", ".title", ".page-title"]
    summary_selectors: [".desc", ".summary", "article p", ".content p"]
    date_selectors: ["time[datetime]", ".date"]
    date_attr: "datetime"

# Мінсоцполітики — новини
- name: "Мінсоцполітики — новини"
  list_urls:
    - "https://www.msp.gov.ua/press-center/news"
  link_selector: ".news-list a, article a, a[href*='/news/']"
  max_per_source: 10
  detail:
    title_selectors: ["h1", ".page-title", ".title"]
    summary_selectors: ["article p", ".content p", ".node__content p"]
    date_selectors: ["time[datetime]", ".date", ".published"]
    date_attr: "datetime"

# Пенсійний фонд України — Пресцентр / Новини
- name: "ПФУ — новини"
  list_urls:
    - "https://www.pfu.gov.ua/prestsentr/novini/"
  link_selector: "article a, .news-item a, a[href*='/novini/']"
  max_per_source: 10
  detail:
    title_selectors: ["h1.entry-title", "h1", ".post-title"]
    summary_selectors: [".entry-content p", "article p", ".post-content p"]
    date_selectors: ["time[datetime]", "time[content]", ".post-date", ".entry-date"]
    date_attr: "datetime"

# Дія — новини/послуги
- name: "Дія — новини"
  list_urls:
    - "https://diia.gov.ua/news"
  link_selector: ".news-list .news-item a, article a, a[href*='/news/']"
  max_per_source: 8
  detail:
    title_selectors: [".news-title", "h1", ".page-title"]
    summary_selectors: [".news-desc", ".summary", "article p", ".content p"]
    date_selectors: ["time[datetime]", ".date"]
    date_attr: "datetime"

# МОЗ — новини
- name: "МОЗ — новини (реабілітація/послуги)"
  list_urls:
    - "https://moz.gov.ua/article/news"
  link_selector: ".news-list .news-item a, article a, a[href*='/article/news']"
  max_per_source: 8
  detail:
    title_selectors: [".title", "h1", ".page-title"]
    summary_selectors: ["article p", ".desc", ".summary"]
    date_selectors: ["time[datetime]", ".date"]
    date_attr: "datetime"
