sources:
  # Міністерство соціальної політики — новини
  - name: "Мінсоцполітики — новини"
    list_urls:
      - "https://www.msp.gov.ua/press-center/news"
    link_selector: "a[href*='/news/'], .news-list a, .views-row a"
    max_per_source: 10
    detail:
      title_selectors: ["h1", ".article-title", ".page-title"]
      summary_selectors: [".article-body p", ".field--name-body p", "article p"]
      date_selectors: ["time[datetime]", ".date", ".published", ".article-date"]
      date_attr: "datetime"

  # Міністерство у справах ветеранів — новини
  - name: "Мінветеранів — новини"
    list_urls:
      - "https://mva.gov.ua/ua/news"
    link_selector: "a[href*='/news/'], .views-row a"
    max_per_source: 10
    detail:
      title_selectors: ["h1", ".node__title", ".page-title"]
      summary_selectors: [".node__content p", ".content p", "article p"]
      date_selectors: ["time[datetime]", ".field--name-created", ".date", ".published"]
      date_attr: "datetime"

  # Пенсійний фонд України — новини
  - name: "ПФУ — новини"
    list_urls:
      - "https://www.pfu.gov.ua/novyny/"
    link_selector: "article a, .news-item a, a[href*='/novyny/']"
    max_per_source: 10
    detail:
      title_selectors: ["h1.entry-title", "h1", ".post-title"]
      summary_selectors: [".entry-content p", "article p", ".post-content p"]
      date_selectors: ["time[datetime]", "time[content]", ".post-date", ".entry-date"]
      date_attr: "datetime"

  # Е-Ветеран — новини
  - name: "Е-Ветеран — новини"
    list_urls:
      - "https://eveteran.gov.ua/novini"
    link_selector: "a[href*='/novini/'], .news a, .views-row a"
    max_per_source: 10
    detail:
      title_selectors: ["h1", ".page-title", ".node__title"]
      summary_selectors: [".content p", "article p"]
      date_selectors: ["time[datetime]", ".date", ".published"]
      date_attr: "datetime"